=== anthonycamilleri/ELM_XSD2JSON/JSON outputs/New folder/edci_contact-generated-schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
     "$id": "http://data.europa.eu/europass/model/edci_contact-generated-schema.json",
    "type": "object",
    "properties": {
        "@targetNamespace": {
            "type": "string",
            "format": "uri",
            "examples": ["http://data.europa.eu/europass/model/credentials#"],
            "default": ""
        },
        "@elementFormDefault": {
            "type": "string",
            "examples": ["qualified"],
            "default": ""
        },
        "@version": {
            "type": "string",
            "examples": ["0.4.0"],
            "default": ""
        },
        "include": {"$ref": "#/definitions/include_type"},
        "complexType": {"$ref": "#/definitions/complexType_type"}
    },
    "additionalProperties": false,
    "definitions": {
        "include_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@schemaLocation": {
                        "type": "string",
                        "examples": ["edci_simpleContentTypes.xsd"],
                        "default": ""
                    }
                },
                "required": ["@schemaLocation"],
                "additionalProperties": false
            },
            "additionalItems": false
        },
        "annotation_type": {
            "type": "object",
            "properties": {
                "documentation": {"type": "null"}
            },
            "additionalProperties": false
        },
        "annotation2_type": {
            "type": "object",
            "properties": {
                "documentation": {
                    "type": "string",
                    "examples": ["The address of an electronic wallet where credentials may be deposited."],
                    "default": ""
                }
            },
            "additionalProperties": false
        },
        "element_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@name": {
                        "type": "string",
                        "examples": ["note"],
                        "default": ""
                    },
                    "@type": {
                        "type": "string",
                        "examples": ["NoteType"],
                        "default": ""
                    },
                    "@minItems": {
                        "type": "string",
                        "examples": ["0"],
                        "default": ""
                    },
                    "@maxItems": {
                        "type": "string",
                        "examples": ["unbounded"],
                        "default": ""
                    },
                    "annotation": {"$ref": "#/definitions/annotation2_type"}
                },
                "required": [
                    "@minItems",
                    "annotation",
                    "@name",
                    "@maxItems",
                    "@type"
                ],
                "additionalProperties": false
            },
            "additionalItems": false
        },
        "sequence_type": {
            "type": "object",
            "properties": {
                "element": {"$ref": "#/definitions/element_type"}
            },
            "additionalProperties": false
        },
        "complexType_type": {
            "type": "object",
            "properties": {
                "@name": {
                    "type": "string",
                    "examples": ["ContactPointType"],
                    "default": ""
                },
                "annotation": {"$ref": "#/definitions/annotation_type"},
                "sequence": {"$ref": "#/definitions/sequence_type"}
            },
            "additionalProperties": false
        }
    }
}

=== anthonycamilleri/ELM_XSD2JSON/JSON outputs/New folder/edci_contact.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.4.0",
   "include": [
      {
         "@schemaLocation": "edci_simpleContentTypes.xsd"
      },
      {
         "@schemaLocation": "edci_commonTypes.xsd"
      }
   ],
   "complexType": {
      "@name": "ContactPointType",
      "annotation": {
         "documentation": null
      },
      "sequence": {
         "element": [
            {
               "@name": "note",
               "@type": "NoteType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "A note about the contactpoint. E.g. a note about the usage and availibility about this contactpoint."
               }
            },
            {
               "@name": "description",
               "@type": "NoteType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "A free text describing the contact details."
               }
            },
            {
               "@name": "address",
               "@type": "AddressType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "A postal address used for contacting the agent."
               }
            },
            {
               "@name": "phone",
               "@type": "PhoneType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "A phone number used for contacting the agent."
               }
            },
            {
               "@name": "mailBox",
               "@type": "MBoxType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "An email address used for contacting the agent."
               }
            },
            {
               "@name": "webresource",
               "@type": "InteractiveWebResourceType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "A contact form used for contacting the agent."
               }
            },
            {
               "@name": "wallet",
               "@type": "MBoxType",
               "@minItems": "0",
               "@maxItems": "unbounded",
               "annotation": {
                  "documentation": "The address of an electronic wallet where credentials may be deposited."
               }
            }
         ]
      }
   }
}
